apiVersion: v1
kind: Pod
metadata:
  name: seldonkanikodebug
spec:
  initContainers:
  - name: init-clone-repo
    image: alpine/git
    args:
        - clone
        - --single-branch
        - --
        - https://github.com/SeldonIO/seldon-core.git
        - /context
    volumeMounts:
    - name: context
      mountPath: /context
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - tail
    args:
    - -f
    - /dev/null
    volumeMounts:
      - name: context
        mountPath: /context
      - name: config
        mountPath: /kaniko/.docker
      - name: config
        mountPath: /root/.docker
  restartPolicy: Never
  volumes:
    - name: config
      secret:
        secretName: config
    - name: context
      emptyDir: {}
